-- Create ethereum_data table (Clone of bitcoin_data)
CREATE TABLE IF NOT EXISTS ethereum_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  close NUMERIC,
  open NUMERIC,
  high NUMERIC,
  low NUMERIC,
  volume NUMERIC,
  sma_50 NUMERIC,
  sma_200 NUMERIC,
  rsi NUMERIC,
  bb_upper NUMERIC,
  bb_lower NUMERIC,
  drawdown_pct NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_ethereum_data_date ON ethereum_data(date DESC);

-- RLS
ALTER TABLE ethereum_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read access" ON ethereum_data;
DROP POLICY IF EXISTS "Service role write access" ON ethereum_data;

CREATE POLICY "Public read access" ON ethereum_data FOR SELECT USING (true);
CREATE POLICY "Service role write access" ON ethereum_data FOR ALL USING (auth.role() = 'service_role');

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE ethereum_data;

-- Trigger
CREATE TRIGGER update_ethereum_data_updated_at
  BEFORE UPDATE ON ethereum_data
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
