-- Create xrp_data table
CREATE TABLE IF NOT EXISTS xrp_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  close NUMERIC,
  open NUMERIC,
  high NUMERIC,
  low NUMERIC,
  volume NUMERIC,
  sma_50 NUMERIC,
  sma_200 NUMERIC,
  rsi NUMERIC,
  bb_upper NUMERIC,
  bb_lower NUMERIC,
  drawdown_pct NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create solana_data table
CREATE TABLE IF NOT EXISTS solana_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  close NUMERIC,
  open NUMERIC,
  high NUMERIC,
  low NUMERIC,
  volume NUMERIC,
  sma_50 NUMERIC,
  sma_200 NUMERIC,
  rsi NUMERIC,
  bb_upper NUMERIC,
  bb_lower NUMERIC,
  drawdown_pct NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_xrp_data_date ON xrp_data(date DESC);
CREATE INDEX IF NOT EXISTS idx_solana_data_date ON solana_data(date DESC);

-- RLS
ALTER TABLE xrp_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE solana_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read access XRP" ON xrp_data FOR SELECT USING (true);
CREATE POLICY "Service role write access XRP" ON xrp_data FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Public read access SOL" ON solana_data FOR SELECT USING (true);
CREATE POLICY "Service role write access SOL" ON solana_data FOR ALL USING (auth.role() = 'service_role');

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE xrp_data;
ALTER PUBLICATION supabase_realtime ADD TABLE solana_data;

-- Triggers
CREATE TRIGGER update_xrp_data_updated_at BEFORE UPDATE ON xrp_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_solana_data_updated_at BEFORE UPDATE ON solana_data FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
