-- ============================================
-- Project Sentinel - Supabase Database Schema
-- Bitcoin Analytics Terminal
-- ============================================

-- Create bitcoin_data table with all OHLCV + calculated indicators
CREATE TABLE IF NOT EXISTS bitcoin_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE UNIQUE NOT NULL,
  close NUMERIC,
  open NUMERIC,
  high NUMERIC,
  low NUMERIC,
  volume NUMERIC,
  sma_50 NUMERIC,       -- 50-day Simple Moving Average
  sma_200 NUMERIC,      -- 200-day Simple Moving Average
  rsi NUMERIC,          -- 14-day Relative Strength Index
  bb_upper NUMERIC,     -- Bollinger Band Upper (20, 2)
  bb_lower NUMERIC,     -- Bollinger Band Lower (20, 2)
  drawdown_pct NUMERIC, -- % Down from All-Time High
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for faster date-based queries
CREATE INDEX IF NOT EXISTS idx_bitcoin_data_date ON bitcoin_data(date DESC);

-- Enable Row Level Security
ALTER TABLE bitcoin_data ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for idempotency)
DROP POLICY IF EXISTS "Public read access" ON bitcoin_data;
DROP POLICY IF EXISTS "Service role write access" ON bitcoin_data;

-- Policy: Allow public SELECT (read-only for frontend)
CREATE POLICY "Public read access" ON bitcoin_data
  FOR SELECT USING (true);

-- Policy: Allow authenticated service role INSERT/UPDATE (for n8n)
CREATE POLICY "Service role write access" ON bitcoin_data
  FOR ALL USING (auth.role() = 'service_role');

-- Enable Realtime for this table
-- Note: Run this in SQL editor as it may require special permissions
ALTER PUBLICATION supabase_realtime ADD TABLE bitcoin_data;

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Drop trigger if exists (for idempotency)
DROP TRIGGER IF EXISTS update_bitcoin_data_updated_at ON bitcoin_data;

-- Trigger for auto-updating timestamp
CREATE TRIGGER update_bitcoin_data_updated_at
  BEFORE UPDATE ON bitcoin_data
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- Useful Queries
-- ============================================

-- Get latest data point
-- SELECT * FROM bitcoin_data ORDER BY date DESC LIMIT 1;

-- Get last 30 days
-- SELECT * FROM bitcoin_data ORDER BY date DESC LIMIT 30;

-- Get data with all calculations for a date range
-- SELECT 
--   date, close, sma_50, sma_200, rsi, 
--   bb_upper, bb_lower, drawdown_pct 
-- FROM bitcoin_data 
-- WHERE date >= NOW() - INTERVAL '1 year'
-- ORDER BY date ASC;
